CREATE DATABASE TDBlog;
USE TDBlog;

CREATE TABLE ROLE
(
	ID NVARCHAR(16) PRIMARY KEY,
    NAME NVARCHAR(30)
);

CREATE TABLE USER
(
	ID NVARCHAR(16) PRIMARY KEY,
    NAME NVARCHAR(30),
    USERNAME NVARCHAR(30),
    PASSWORD NVARCHAR(30),
    REGISTEREDAT DATETIME,
    ROLEID NVARCHAR(16)
);

CREATE TABLE POST
(
	ID NVARCHAR(16) PRIMARY KEY,
    NAME NVARCHAR(256),
    CONTENT NVARCHAR(4000),
    VIEW INT,
    TIME INT,
    CREATEDAT DATETIME,
    UPDATEDAT DATETIME,
    AUTHORID NVARCHAR(16),
    TAGID NVARCHAR(16)
);

CREATE TABLE STATEHISTORY
(
	ID NVARCHAR(16),
    STATE INT,
    AT DATETIME,
    POSTID NVARCHAR(16)
);

CREATE TABLE TAG 
(
	ID NVARCHAR(16) PRIMARY KEY,
    NAME NVARCHAR(256)
);


ALTER TABLE USER
	ADD CONSTRAINT FK_USER_ROLE
    FOREIGN KEY (ROLEID)
    REFERENCES ROLE(ID);
ALTER TABLE POST
	ADD CONSTRAINT FK_POST_AUTHOR
    FOREIGN KEY (AUTHORID)
    REFERENCES USER(ID);
ALTER TABLE POST
	ADD CONSTRAINT FK_TAG_POST
    FOREIGN KEY (TAGID)
    REFERENCES TAG(ID);
ALTER TABLE STATEHISTORY
	ADD CONSTRAINT FK_STATE_POST
    FOREIGN KEY (POSTID)
    REFERENCES POST(ID);
    
INSERT INTO ROLE(ID, NAME)
VALUES('ROLE_01', 'ADMIN');
INSERT INTO ROLE(ID, NAME)
VALUES('ROLE_02', 'USER');

INSERT INTO TAG(ID, NAME)
VALUES('TAG_01', 'Khoa học - Công nghệ');
INSERT INTO TAG(ID, NAME)
VALUES('TAG_02', 'Sách');
INSERT INTO TAG(ID, NAME)
VALUES('TAG_03', 'Du lịch');
INSERT INTO TAG(ID, NAME)
VALUES('TAG_04', 'Đời sống hằng ngày');
INSERT INTO TAG(ID, NAME)
VALUES('TAG_05', 'Phát triển bản thân');
INSERT INTO TAG(ID, NAME)
VALUES('TAG_06', 'Quan điểm - Tranh luận');
INSERT INTO TAG(ID, NAME)
VALUES('TAG_07', 'Thể thao');